name: Docker Image CI

on:
  push:
    branches: [ "main" ]
   # tags:
    #  - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest 
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js (v20.19.0 for Angular 20+)
      uses: actions/setup-node@v4
      with:
        node-version: 20.19.0

    - name: Install packages and build Angular
      run: |
        cd android-angular
        npm install
        npm run build

   
    - name: Get version from package.json
      id: get_version
      run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

    - name: Check if tag exists
      run: |
        if git rev-parse v${{ steps.get_version.outputs.version }} >/dev/null 2>&1; then
          echo "Tag v${{ steps.get_version.outputs.version }} already exists"
        fi
