name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js (v20.19.0 for Angular 20+)
      uses: actions/setup-node@v4
      with:
        node-version: 20.19.0

    - name: Install packages and build Angular
      run: |
        cd android-angular
        npm install
        npm run build

    - name: Install Cordova
      run: npm install -g cordova

    - name: Clean previous Cordova project if exists
      run: rm -rf androidtimp

    - name: Cordova project setup
      run: |
        cordova create androidtimp com.thinkrms.timp TIMP
        cd androidtimp
        cordova platform add android@13.0.0

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Remove default Cordova www directory
      run: rm -rf androidtimp/www/

    - name: Copy Angular build to Cordova www
      run: |
        DIST_DIR=$(ls android-angular/dist)
        cp -r android-angular/dist/$DIST_DIR androidtimp/www

    - name: Build APK
      run: |
        cd androidtimp
        cordova build android

   
   
    - name: Upload Release APK
      uses: softprops/action-gh-release@v1
      with:
        files: /home/runner/work/android-cordova/android-cordova/androidtimp/platforms/android/app/build/outputs/apk/debug/app-debug.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - name: Get current date and short SHA
      id: vars
      run: |
        echo "date_tag=v$(date +'%Y.%m.%d')-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Create tag
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag ${{ steps.vars.outputs.date_tag }}
        git push origin ${{ steps.vars.outputs.date_tag }}
    #//- name: upload binaries to release
      #uses: softprops/action-gh-release@v1
     # if: ${{startsWith(github.ref, 'refs/tags/v1.0.0') }}
      #with:
       # files: /home/runner/work/android-cordova/android-cordova/androidtimp/platforms/android/app/build/outputs/apk/debug/app-debug.apk
